
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LAGK = 9;
  public static final int STRING_LITERAL = 13;
  public static final int EOF = 0;
  public static final int PREFIX = 7;
  public static final int PLUS = 2;
  public static final int IF = 5;
  public static final int ELSE = 6;
  public static final int COMMA = 11;
  public static final int error = 1;
  public static final int PARAGK = 12;
  public static final int RPAREN = 4;
  public static final int IDENTIFIER = 14;
  public static final int RAGK = 10;
  public static final int SUFFIX = 8;
  public static final int LPAREN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "IF",
  "ELSE",
  "PREFIX",
  "SUFFIX",
  "LAGK",
  "RAGK",
  "COMMA",
  "PARAGK",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

